#!/usr/bin/env python3
"""Generate error-function polynomials from rational enclosures, no source tables.

The Gaussian integral gives an alternating series at zero and positive moment
ratios at positive centers. Adjacent continued-fraction convergents enclose the
anchor; the differential equation generates all derivatives. Both endpoints
must round to the same binary64 word. Only Python's standard library is used.
"""
import argparse
from fractions import Fraction as F
from functools import lru_cache
from math import factorial
from pathlib import Path
import re

DEGREE = 16
CELLS = 48
TAIL_DEGREE = 12
ERF_DEGREE = 13
ROOT = Path(__file__).resolve().parent.parent


def plus(a, b): return a[0]+b[0], a[1]+b[1]
def minus(a, b): return a[0]-b[1], a[1]-b[0]
def times(a, x): return (a[0]*x,a[1]*x) if x >= 0 else (a[1]*x,a[0]*x)
def rounded(a):
    x, y = map(float,a)
    assert x == y, 'rational enclosure does not resolve coefficient rounding'
    return x


@lru_cache(None)
def constant():
    # Existing independently derived Machin/integer-square-root enclosure.
    from kernel_certificates import inverse_sqrt_pi
    return inverse_sqrt_pi()


def series_coefficients(n):
    result=[(F(1),F(1)),times(constant(),-2)]
    for k in range(2,n+1):result.append(times(result[k-2],F(2,k)))
    return result


def anchor(x):
    if x < 2:
        # Even/odd Taylor polynomials of exp(-2xt), integrated against
        # exp(-t²), bracket the result on the entire positive real axis.
        cs=series_coefficients(161)
        total=(F(0),F(0))
        for k in range(161):total=plus(total,times(cs[k],x**k))
        lower=plus(total,times(cs[161],x**161))[0]
        return lower,total[1]
    def convergent(depth):
        ratio=F(0)
        for n in range(depth,0,-1):ratio=F(n,2)/(x+ratio)
        return 1/(x+ratio)
    a,b=sorted([convergent(512),convergent(513)])
    lo,hi=constant()
    return lo*a,hi*b


def local_coefficients(center):
    cs=[anchor(center)]
    cs.append(minus(times(cs[0],2*center),times(constant(),2)))
    for n in range(2,DEGREE+1):
        cs.append(times(plus(times(cs[n-1],2*center),times(cs[n-2],2)),F(1,n)))
    return cs


def small_coefficients():
    return [times(constant(),F(2*(-1)**k,factorial(k)*(2*k+1))) for k in range(ERF_DEGREE+1)]


def tail_coefficients():
    cs=[F(1)]
    for k in range(1,TAIL_DEGREE+1):cs.append(-cs[-1]*F(2*k-1,2))
    return cs


def values():
    return {'small': [rounded(x) for x in small_coefficients()],
            'tail': [float(x) for x in tail_coefficients()],
            'local': [[rounded(x) for x in local_coefficients(F(2*i+1,8))] for i in range(CELLS)],
            'local_low': [rounded(minus(anchor(F(2*i+1,8)), (F(rounded(anchor(F(2*i+1,8)))),)*2)) for i in range(CELLS)]}


def render():
    data=values()
    result=['(* Generated by oracle/erf_coefficients.py from rational Gaussian-integral enclosures. *)',
            'let inv_sqrt_pi = '+rounded(constant()).hex()]
    for key in ['small','tail','local_low']:
        result += ['let '+key+' = [| '+ '; '.join(x.hex() for x in data[key])+' |]']
    result += ['let local = [|']
    result += ['  [| '+'; '.join(x.hex() for x in row)+' |];' for row in data['local']]
    result += ['|]']
    return '\n'.join(result)+'\n'


def read():
    source=(ROOT/'lib/erf_coefficients.ml').read_text()
    def nums(s):return [float.fromhex(x) for x in re.findall(r'-?0x[0-9a-f.]+p[+-]?[0-9]+',s)]
    names=['inv_sqrt_pi','small','tail','local_low','local'];parts={}
    for i,name in enumerate(names):
        s=source.split('let '+name+' =',1)[1]
        if i+1<len(names):s=s.split('let '+names[i+1],1)[0]
        parts[name]=nums(s)
    assert len(parts['inv_sqrt_pi'])==1 and parts['inv_sqrt_pi'][0]==rounded(constant())
    assert len(parts['local'])==CELLS*(DEGREE+1)
    parts['local']=[parts['local'][i*(DEGREE+1):(i+1)*(DEGREE+1)] for i in range(CELLS)]
    return parts


def check():
    actual=read();expected=values()
    for k in expected:assert actual[k]==expected[k],k
    return actual


if __name__=='__main__':
    p=argparse.ArgumentParser(description=__doc__)
    p.add_argument('--check',action='store_true')
    p.add_argument('--version',action='version',version='erf_coefficients 1')
    a=p.parse_args()
    if a.check:
        check();print('All generated error-function coefficients verified by rational enclosures')
    else:print(render(),end='')
