(library
 (name morphiq_risk)
 (public_name morphiq_risk_ml)
 (libraries morphiq_fp)
 (foreign_stubs
  (language c)
  (names bachelier_kernel_stubs)
  (flags
   (:standard
    -O3
    -ffp-contract=off
    -fno-fast-math
    -fno-tree-vectorize
    -fno-tree-slp-vectorize)))
 (c_library_flags -lm)
 (flags
  (:standard -strict-sequence -w +a-4-40-41-42-44-45-70 -open Morphiq_fp))
 (ocamlopt_flags
  (:standard -O3)))
